Create model
byiringiroscar/wikipedia-project-with-rails pull request #1
Opened 2023-06-13 21:35 UTC by byiringiroscar

### Create model😄 
#### What does this PR do ❓ 
####  Create Model
This PR is raised to implement the following features 🆗 :

- [x] Add Model
- [x] Setup linters

### How should it be tested ⬇️ ⬇️ ⬇️ 

clone this repository
     
```
git clone https://github.com/byiringiroscar/wikipedia-project-with-rails
```
Navigate to folder
```
cd wikipedia-project-with-rails
```
Switch to this feature/create-model
```
git switch feature/create-model
```
Run project and Installation
- open the command prompt and run :
```
bundle install
```
```
rails s
```

### Thanks for reviewing my PR 😄

2023-06-13 22:18 UTC, t-yanick requested changes
# STATUS: CHANGES REQUIRED

Hi @byiringiroscar , 

### Good job so far!
### To Highlight! :clap:  :green_circle: 

:heavy_check_mark:  Effective use of postgresql 
:heavy_check_mark: Migrations for all models present
:heavy_check_mark: Use of correct Gitflow


There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-13 22:18 UTC, t-yanick commented on README.md
> +- [No link yet]()
- [ ] Great job working on this mile stone. If you wish to write `No link yet`, kindly remove all the brackets so that the markdown does not display as a link which is broken when clicked.
![image](https://github.com/byiringiroscar/wikipedia-project-with-rails/assets/62849872/8b8df3ff-9043-4937-8c50-41cb26794d3b)

2023-06-13 22:18 UTC, t-yanick commented on db/migrate/20230613201507_create_users.rb
> +      t.string :string
- [ ] From the [ERD](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/images/blog_app_erd.png) there is no column in the `User` table as `string`. Kindly delete this column and ensure your migration follows the given ERD.

2023-06-13 22:18 UTC, t-yanick commented on db/migrate/20230613201507_create_users.rb
> +      t.string :string
- [ ] From the [ERD](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/images/blog_app_erd.png) there is no column in the `User` table as `string`. Kindly delete this column and ensure your migration follows the given ERD.

2023-06-13 22:18 UTC, t-yanick commented on db/migrate/20230613201911_create_posts.rb
> +      t.string :integer
- [ ] From the [ERD](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/images/blog_app_erd.png) there is no column in the `Post` table as `integer`. Kindly delete this column and ensure your migration follows the given ERD.

2023-06-13 22:18 UTC, t-yanick commented on db/migrate/20230613201911_create_posts.rb
> +      t.string :string
- [ ] From the [ERD](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/images/blog_app_erd.png) there is no column in the `Post` table as `string`. Kindly delete this column and ensure your migration follows the given ERD.

2023-06-13 22:18 UTC, t-yanick commented on db/migrate/20230613201911_create_posts.rb
> +      t.string :integer
- [ ] From the [ERD](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/images/blog_app_erd.png) there is no column in the `Post` table as `integer`. Kindly delete this column and ensure your migration follows the given ERD.

2023-06-13 22:18 UTC, t-yanick commented on db/migrate/20230613201911_create_posts.rb
> +      t.string :integer
- [ ] From the [ERD](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/images/blog_app_erd.png) there is no column in the `Post` table as `integer`. Kindly delete this column and ensure your migration follows the given ERD.

2023-06-13 22:18 UTC, t-yanick commented on db/migrate/20230613205213_create_comments.rb
> +      t.string :integer
- [ ] From the [ERD](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/images/blog_app_erd.png) there is no column in the `Comment` table as `integer`. Kindly delete this column and ensure your migration follows the given ERD.

2023-06-13 22:18 UTC, t-yanick commented on db/migrate/20230613205213_create_comments.rb
> +      t.string :integer
- [ ] From the [ERD](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/images/blog_app_erd.png) there is no column in the `Comment` table as `integer`. Kindly delete this column and ensure your migration follows the given ERD.

2023-06-13 22:18 UTC, t-yanick commented on db/migrate/20230613201911_create_posts.rb
> +      t.string :AuthorId
- [ ] Great job so far. We still have some work to do. You have not added indexes for foreign keys. As per project requirements: `All columns that are foreign keys should have a corresponding index.` We have foreign keys in thr posts, comments and likes table. Kindly add the indexes of the respective foreign keys.
![image](https://github.com/byiringiroscar/wikipedia-project-with-rails/assets/62849872/1348503c-85d4-4c8e-b577-cc98799e6f01)

2023-06-14 07:36 UTC, Davidosky007 approved these changes
Hi @byiringiroscar 👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
* Database migration files  used to maintain database schema 👍 
* Well written PR 👍 
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-14 07:40 UTC, merged